name: "Adiciona Issues em Projects GitHub"
  
on:
  issues:
    types:
      - opened
jobs:
  add-issue:
    uses: "mentoriaiac/cicd_centralizado/.github/workflows/add_issues_projects.yaml@v1"
    with:
      project-url: https://github.com/orgs/mentoriaiac/projects/6
      github_token: ${{ secrets.ADD_TO_PROJECT_PAT }}
